# permissions for end users to view octaviaamphoracontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octaviaamphoracontroller-viewer-role
rules:
- apiGroups:
  - octavia.openstack.org
  resources:
  - octaviaamphoracontrollerss
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - octavia.openstack.org
  resources:
  - octaviaamphoracontrollers/status
  verbs:
  - get
