# permissions for end users to edit octaviaapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octavia-editor-role
rules:
- apiGroups:
  - octavia.openstack.org
  resources:
  - octavia
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - octavia.openstack.org
  resources:
  - octavia/status
  verbs:
  - get
