# permissions for end users to view octaviaapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octavia-viewer-role
rules:
- apiGroups:
  - octavia.openstack.org
  resources:
  - octavia
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - octavia.openstack.org
  resources:
  - octavia/status
  verbs:
  - get
