# permissions for end users to view octaviaapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octaviaapi-viewer-role
rules:
- apiGroups:
  - octavia.openstack.org
  resources:
  - octaviaapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - octavia.openstack.org
  resources:
  - octaviaapis/status
  verbs:
  - get
