# permissions for end users to edit octaviaamphoracontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octaviaamphoracontroller-editor-role
rules:
- apiGroups:
  - octavia.openstack.org
  resources:
  - octaviaamphoracontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - octavia.openstack.org
  resources:
  - octaviaamphoracontrollers/status
  verbs:
  - get
