apiVersion: octavia.openstack.org/v1beta1
kind: Octavia
metadata:
  name: octavia
spec:
  # TODO(tweining): Add fields here
  databaseInstance: openstack
  databaseUser: octavia
  serviceUser: octavia
  replicas: 1
  secret: osp-secret
  # passwordSelectors: TODO
  # nodeSelector: TODO
  debug:
    dbSync: false
    service: false
  preserveJobs: false
  customServiceConfig: |
    [DEFAULT]
    debug = true
  resources:
    requests:
      memory: "500Mi"
      cpu: "1.0"
  octaviaAPI:
    databaseInstance: openstack
    databaseUser: octavia
    serviceUser: octavia
    containerImage: quay.io/tripleozedcentos9/openstack-octavia-api:current-tripleo
    replicas: 1
    secret: osp-secret
    # passwordSelectors: TODO
    # nodeSelector: TODO
    debug:
      dbSync: false
      service: false
    preserveJobs: false
    customServiceConfig: |
      [DEFAULT]
      debug = true
    resources:
      requests:
        memory: "500Mi"
        cpu: "1.0"

