apiVersion: octavia.openstack.org/v1beta1
kind: Octavia
metadata:
  name: octavia
spec:
  # TODO(tweining): Add fields here
  databaseInstance: openstack
  databaseUser: octavia
  serviceUser: octavia
  secret: osp-secret
  # passwordSelectors: TODO
  # nodeSelector: TODO
  debug:
    dbSync: false
    service: false
  preserveJobs: false
  customServiceConfig: |
    [DEFAULT]
    debug = true
  octaviaAPI:
    databaseInstance: openstack
    databaseUser: octavia
    serviceUser: octavia
    serviceAccount: octavia
    secret: osp-secret
    # passwordSelectors: TODO
    # nodeSelector: TODO
    debug:
      dbSync: false
      service: false
    preserveJobs: false
    customServiceConfig: |
      [DEFAULT]
      debug = true
